### PR TITLE
update: run container as non root

### PR DESCRIPTION
**Pull request by codekow**
- Updated: `Dockerfile` to run as a non-root user (1001)
- Updated: docker-compose.yml (vbmc to vsbmc)
- Added: container quickstart docs

### CODE REVIEW

**Comment by codekow** [comment]
Let me know how you feel about these updates and anything you might want changed.

**Comment by kurokobo** [comment]
Thanks for creating this PR! This looks good for me, I didn't document this anywhere but making the container as non-rooted was on the roadmap in my mind :)

I don't have a time to maintain this project in these days, but I'll merge this when I rename the commands as mentioned in #9.

**Comment by codekow** [comment]
Sounds good. Totally understand. :+1:

**Comment by kurokobo** [comment]
Merged with a few changes to the PR. Thanks for your contribution again!

The guide for the containerized environment has been available on the [wiki page](https://github.com/kurokobo/virtualbmc-for-vsphere/wiki/Containerized-VirtualBMC-for-vSphere), so I've made some improvements to that page.

**Pull request merged**
